## Step 4 — Describe Dataset Purpose

### 1. Load Dataset

In [1]:
import pandas as pd

# Load dataset (ubah path sesuai lokasi file Anda)
file_path = r"C:\Users\Michael Marcel\OneDrive\Desktop\TA\Data\Dataset\student_lifestyle_100k.csv"

df = pd.read_csv(file_path)

df.head()

,Student_ID,Age,Gender,Department,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression
0,1001,22,Female,Science,3.50,7.3,3.3,3.4,114,5,False
1,1002,20,Male,Engineering,2.72,5.5,7.2,6.0,142,2,False
2,1003,20,Male,Medical,3.01,5.4,2.3,1.8,137,3,False
3,1004,21,Male,Engineering,3.63,8.1,2.0,4.6,130,3,False
4,1005,19,Male,Arts,3.14,6.8,2.6,4.3,4,6,False

### 2. Ringkasan Variabel

In [2]:
# Step 4.1 - Dataset basic information
print("Jumlah baris dan kolom:", df.shape)

print("\nDaftar kolom:")
print(df.columns.tolist())

Jumlah baris dan kolom: (100000, 11)

Daftar kolom:
['Student_ID', 'Age', 'Gender', 'Department', 'CGPA', 'Sleep_Duration', 'Study_Hours', 'Social_Media_Hours', 'Physical_Activity', 'Stress_Level', 'Depression']

In [3]:
# Step 4.2 - Sample data preview
df.sample(5)

,Student_ID,Age,Gender,Department,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression
85865,86866,21,Male,Business,3.20,8.0,3.1,5.7,143,2,True
50711,51712,23,Male,Engineering,2.81,6.7,3.8,0.6,13,5,False
43627,44628,22,Female,Arts,2.17,8.0,6.1,4.9,53,3,False
46685,47686,19,Female,Engineering,2.18,6.0,6.2,4.6,89,3,False
16715,17716,20,Female,Business,2.17,9.1,3.9,3.3,58,6,False

In [4]:
# Step 4.3 - Descriptive statistics
df.describe(include="all")

,Student_ID,Age,Gender,Department,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression
count,100000.000000,100000.000000,100000,100000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000
unique,NaN,NaN,2,5,NaN,NaN,NaN,NaN,NaN,NaN,2
top,NaN,NaN,Male,Science,NaN,NaN,NaN,NaN,NaN,NaN,False
freq,NaN,NaN,50120,20071,NaN,NaN,NaN,NaN,NaN,NaN,89938
mean,51000.500000,21.009010,NaN,NaN,2.898316,6.996425,4.509517,3.503288,74.353180,4.131660,NaN
std,28867.657797,2.000382,NaN,NaN,0.532240,1.498682,1.976076,1.486852,43.366963,1.424151,NaN
min,1001.000000,18.000000,NaN,NaN,1.560000,3.000000,0.000000,0.000000,0.000000,2.000000,NaN
25%,26000.750000,19.000000,NaN,NaN,2.450000,6.000000,3.200000,2.500000,37.000000,3.000000,NaN
50%,51000.500000,21.000000,NaN,NaN,2.900000,7.000000,4.500000,3.500000,74.000000,4.000000,NaN
75%,76000.250000,23.000000,NaN,NaN,3.350000,8.000000,5.800000,4.500000,112.000000,5.000000,NaN
max,101000.000000,24.000000,NaN,NaN,4.000000,12.000000,12.800000,10.000000,149.000000,10.000000,NaN

### Dataset Context / Purpose

Data berisi identitas dasar seperti usia, jenis kelamin, dan departemen, serta indikator performa akademik yang ditunjukkan melalui nilai Indeks Prestasi Kumulatif (CGPA). Dataset juga merekam berbagai aspek perilaku keseharian mahasiswa yang berpotensi memengaruhi kesejahteraan dan kinerja akademik.

Variabel gaya hidup yang diamati meliputi durasi tidur, lama waktu belajar, intensitas penggunaan media sosial yang berhubungan dengan keberhasilan akademik (IPK/CGPA) dan masalah kesehatan mental (Depression & Stress). Dataset ini juga memasukkan variabel psikologis seperti tingkat stres dan indikasi depresi, sehingga memungkinkan analisis tentang hubungan antara pola hidup, kesehatan mental, dan pencapaian akademik mahasiswa.

Secara umum, dataset ini bertujuan untuk mengidentifikasi faktor-faktor yang berpengaruh terhadap kesejahteraan dan performa akademik mahasiswa. Hasil analisis diharapkan dapat menjadi dasar pengambilan keputusan dalam upaya peningkatan kualitas hidup dan keberhasilan studi mahasiswa.

In [5]:
categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    print(f"\n{col} unique values:")
    print(df[col].unique())

Gender unique values:
<StringArray>
['Female', 'Male']
Length: 2, dtype: str

Department unique values:
<StringArray>
['Science', 'Engineering', 'Medical', 'Arts', 'Business']
Length: 5, dtype: str

C:\Users\Michael Marcel\AppData\Local\Temp\ipykernel_23912\1376859987.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns